### ISSUE TITLE
Cannot satisfy package QuickCheck

### ISSUE THREAD

**Issue by newhoggy** [haskell-mafia/mafia#126]
Hello,

I'm trying to get back into Haskell develop, but my projects look like they don't build anymore:

```
Preprocessing test suite 'hw-diagnostics-test' for hw-diagnostics-0.0.0.2...
<command line>: cannot satisfy -package-id QuickCheck-2.8.1-8f3828a4d4d9dac78c5d3db525b2f0fe
    (use -v for more information)
Process failed: cabal build -j --ghc-options=-Werror (exit code: 1)
```

Is there a way to fix this?

Thanks!

**Comment by erikd-ambiata** [comment]
Try `./mafia clean` followed by `./mafia upgrade` and then `./mafia build`.

**Comment by newhoggy** [comment]
I get a different error this time:

```
07:57 $ mafia build
Building mafia-de245376fd86c1ec9a5a451f096cb79bc8ae68f7 in /var/folders/v8/mpmmts8946j10dzhv2gxvt1h0000gp/T/tmp.2WNbluE5
Cloning into 'mafia'...
remote: Counting objects: 1467, done.
remote: Total 1467 (delta 0), reused 0 (delta 0), pack-reused 1467
Receiving objects: 100% (1467/1467), 469.93 KiB | 88.00 KiB/s, done.
Resolving deltas: 100% (782/782), done.
Checking connectivity... done.
HEAD is now at de24537 Merge pull request #124 from ambiata/topic/oops
Submodule 'lib/disorder' (https://github.com/ambiata/disorder.hs) registered for path 'lib/disorder'
Submodule 'lib/p' (https://github.com/ambiata/p) registered for path 'lib/p'
Submodule 'lib/twine' (https://github.com/ambiata/twine) registered for path 'lib/twine'
Submodule 'lib/x' (https://github.com/ambiata/x) registered for path 'lib/x'
Cloning into 'lib/disorder'...
remote: Counting objects: 1421, done.
remote: Total 1421 (delta 0), reused 0 (delta 0), pack-reused 1421
Receiving objects: 100% (1421/1421), 305.18 KiB | 75.00 KiB/s, done.
Resolving deltas: 100% (547/547), done.
Checking connectivity... done.
Submodule path 'lib/disorder': checked out 'c8625df58098d78cfa71cfb578bf72ccc2836706'
Cloning into 'lib/p'...
remote: Counting objects: 748, done.
remote: Total 748 (delta 0), reused 0 (delta 0), pack-reused 747
Receiving objects: 100% (748/748), 107.73 KiB | 0 bytes/s, done.
Resolving deltas: 100% (345/345), done.
Checking connectivity... done.
Submodule path 'lib/p': checked out 'fd88f397585914b1d897a5ec5dc5862a4fea9833'
Cloning into 'lib/twine'...
remote: Counting objects: 350, done.
remote: Total 350 (delta 0), reused 0 (delta 0), pack-reused 350
Receiving objects: 100% (350/350), 53.81 KiB | 0 bytes/s, done.
Resolving deltas: 100% (134/134), done.
Checking connectivity... done.
Submodule path 'lib/twine': checked out '23d611a131785da696760000f148e7f14f26e277'
Cloning into 'lib/x'...
remote: Counting objects: 1499, done.
remote: Total 1499 (delta 0), reused 0 (delta 0), pack-reused 1499
Receiving objects: 100% (1499/1499), 242.16 KiB | 151.00 KiB/s, done.
Resolving deltas: 100% (503/503), done.
Checking connectivity... done.
Submodule path 'lib/x': checked out '5c2e9b1ed04402f655ed7c1b7a8de42bc42b5000'
Writing a default package environment file to
/private/var/folders/v8/mpmmts8946j10dzhv2gxvt1h0000gp/T/tmp.2WNbluE5/mafia/cabal.sandbox.config
Creating a new sandbox at
/private/var/folders/v8/mpmmts8946j10dzhv2gxvt1h0000gp/T/tmp.2WNbluE5/mafia/.cabal-sandbox
Downloading the latest package list from hackage.haskell.org
Skipping download: Local and remote files match.
Resolving dependencies...
Notice: installing into a sandbox located at
/private/var/folders/v8/mpmmts8946j10dzhv2gxvt1h0000gp/T/tmp.2WNbluE5/mafia/.cabal-sandbox
Configuring SafeSemaphore-0.10.1...
Configuring ambiata-x-exception-0.0.1...
Configuring ansi-terminal-0.6.2.3...
Configuring base-orphans-0.5.4...
Configuring base16-bytestring-0.1.1.6...
Configuring dlist-0.7.1.2...
Configuring fail-4.9.0.0...
Configuring filelock-0.1.0.1...
Downloading process-1.4.2.0...
Downloading time-locale-compat-0.1.1.3...
Building ansi-terminal-0.6.2.3...
Building SafeSemaphore-0.10.1...
Building ambiata-x-exception-0.0.1...
Failed to install SafeSemaphore-0.10.1
Build log ( /private/var/folders/v8/mpmmts8946j10dzhv2gxvt1h0000gp/T/tmp.2WNbluE5/mafia/.cabal-sandbox/logs/SafeSemaphore-0.10.1.log ):
Configuring SafeSemaphore-0.10.1...
Building SafeSemaphore-0.10.1...
Preprocessing library SafeSemaphore-0.10.1...
<command line>: cannot satisfy -package-id stm-2.4.4-11b941936fbe7d69a733b3786e113e1a
    (use -v for more information)
Failed to install ambiata-x-exception-0.0.1
Build log ( /private/var/folders/v8/mpmmts8946j10dzhv2gxvt1h0000gp/T/tmp.2WNbluE5/mafia/.cabal-sandbox/logs/ambiata-x-exception-0.0.1.log ):
Configuring ambiata-x-exception-0.0.1...
Building ambiata-x-exception-0.0.1...
Preprocessing library ambiata-x-exception-0.0.1...
<command line>: cannot satisfy -package-id exceptions-0.8.0.2-7743311b81466c45b79980529f7392e8
    (use -v for more information)
Configuring memory-0.12...
Configuring monad-loops-0.4.3...
Building base16-bytestring-0.1.1.6...
Building base-orphans-0.5.4...
Building dlist-0.7.1.2...
Building filelock-0.1.0.1...
Building fail-4.9.0.0...
Building monad-loops-0.4.3...
Building memory-0.12...
Configuring tagged-0.8.4...
Installed fail-4.9.0.0
Configuring temporary-1.2.0.4...
Installed base16-bytestring-0.1.1.6
Configuring tar-0.4.5.0...
Installed filelock-0.1.0.1
Building tagged-0.8.4...
Building temporary-1.2.0.4...
Configuring time-locale-compat-0.1.1.3...
Failed to install temporary-1.2.0.4
Build log ( /private/var/folders/v8/mpmmts8946j10dzhv2gxvt1h0000gp/T/tmp.2WNbluE5/mafia/.cabal-sandbox/logs/temporary-1.2.0.4.log ):
Configuring temporary-1.2.0.4...
Building temporary-1.2.0.4...
Preprocessing library temporary-1.2.0.4...
<command line>: cannot satisfy -package-id exceptions-0.8.0.2-7743311b81466c45b79980529f7392e8
    (use -v for more information)
Configuring process-1.4.2.0...
Installed dlist-0.7.1.2
Building tar-0.4.5.0...
Building time-locale-compat-0.1.1.3...
Installed monad-loops-0.4.3
Installed time-locale-compat-0.1.1.3
Installed ansi-terminal-0.6.2.3
Configuring ansi-wl-pprint-0.6.7.3...
Building process-1.4.2.0...
Installed tagged-0.8.4
Configuring semigroups-0.18.2...
Building ansi-wl-pprint-0.6.7.3...
Building semigroups-0.18.2...
Failed to install semigroups-0.18.2
Build log ( /private/var/folders/v8/mpmmts8946j10dzhv2gxvt1h0000gp/T/tmp.2WNbluE5/mafia/.cabal-sandbox/logs/semigroups-0.18.2.log ):
Configuring semigroups-0.18.2...
Building semigroups-0.18.2...
Preprocessing library semigroups-0.18.2...
<command line>: cannot satisfy -package-id hashable-1.2.3.3-0878f5277d2f75c9c528bcea05099169
    (use -v for more information)
Installed ansi-wl-pprint-0.6.7.3
Installed process-1.4.2.0
Downloading Cabal-1.24.0.0...
Configuring optparse-applicative-0.12.1.0...
Configuring Cabal-1.24.0.0...
Installed memory-0.12
Configuring cryptonite-0.15...
Building optparse-applicative-0.12.1.0...
Failed to install optparse-applicative-0.12.1.0
Build log ( /private/var/folders/v8/mpmmts8946j10dzhv2gxvt1h0000gp/T/tmp.2WNbluE5/mafia/.cabal-sandbox/logs/optparse-applicative-0.12.1.0.log ):
Configuring optparse-applicative-0.12.1.0...
Building optparse-applicative-0.12.1.0...
Preprocessing library optparse-applicative-0.12.1.0...
<command line>: cannot satisfy -package-id transformers-compat-0.4.0.4-8aa4073730c676dbe210ea8bffd8d092
    (use -v for more information)
Building cryptonite-0.15...
Installed base-orphans-0.5.4
Configuring distributive-0.5.0.2...
Installed tar-0.4.5.0
Building distributive-0.5.0.2...
Failed to install distributive-0.5.0.2
Build log ( /private/var/folders/v8/mpmmts8946j10dzhv2gxvt1h0000gp/T/tmp.2WNbluE5/mafia/.cabal-sandbox/logs/distributive-0.5.0.2.log ):
[1 of 1] Compiling Main             ( /var/folders/v8/mpmmts8946j10dzhv2gxvt1h0000gp/T/cabal-tmp-54531/distributive-0.5.0.2/dist/dist-sandbox-1869144d/setup/setup.hs, /var/folders/v8/mpmmts8946j10dzhv2gxvt1h0000gp/T/cabal-tmp-54531/distributive-0.5.0.2/dist/dist-sandbox-1869144d/setup/Main.o )
Linking /var/folders/v8/mpmmts8946j10dzhv2gxvt1h0000gp/T/cabal-tmp-54531/distributive-0.5.0.2/dist/dist-sandbox-1869144d/setup/setup ...
Configuring distributive-0.5.0.2...
Building distributive-0.5.0.2...
Preprocessing library distributive-0.5.0.2...
<command line>: cannot satisfy -package-id transformers-compat-0.4.0.4-8aa4073730c676dbe210ea8bffd8d092
    (use -v for more information)
Building Cabal-1.24.0.0...
Installed cryptonite-0.15
Warning:
/var/folders/v8/mpmmts8946j10dzhv2gxvt1h0000gp/T/pkgConf-Cabal-1.24.02014119113515204530.0:
Unrecognized field abi on line 69
Installed Cabal-1.24.0.0
Updating documentation index
/private/var/folders/v8/mpmmts8946j10dzhv2gxvt1h0000gp/T/tmp.2WNbluE5/mafia/.cabal-sandbox/share/doc/x86_64-osx-ghc-7.10.3/index.html
cabal: Error: some packages failed to install:
SafeSemaphore-0.10.1 failed during the building phase. The exception was:
ExitFailure 1
aeson-0.11.2.0 depends on semigroups-0.18.2 which failed to install.
ambiata-mafia-0.0.1 depends on distributive-0.5.0.2 which failed to install.
ambiata-p-0.0.1 depends on distributive-0.5.0.2 which failed to install.
ambiata-twine-0.0.1 depends on distributive-0.5.0.2 which failed to install.
ambiata-x-eithert-0.0.1 depends on ambiata-x-exception-0.0.1 which failed to
install.
ambiata-x-exception-0.0.1 failed during the building phase. The exception was:
ExitFailure 1
ambiata-x-optparse-0.0.1 depends on optparse-applicative-0.12.1.0 which failed
to install.
bifunctors-5.2 depends on distributive-0.5.0.2 which failed to install.
comonad-5 depends on distributive-0.5.0.2 which failed to install.
contravariant-1.4 depends on semigroups-0.18.2 which failed to install.
distributive-0.5.0.2 failed during the building phase. The exception was:
ExitFailure 1
optparse-applicative-0.12.1.0 failed during the building phase. The exception
was:
ExitFailure 1
semigroups-0.18.2 failed during the building phase. The exception was:
ExitFailure 1
temporary-1.2.0.4 failed during the building phase. The exception was:
ExitFailure 1
void-0.7.1 depends on semigroups-0.18.2 which failed to install.
```

**Comment by newhoggy** [comment]
I am using:

```
08:13 $ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.3
```

**Comment by erikd-ambiata** [comment]
Basically its all in:

```
Building semigroups-0.18.2...
Failed to install semigroups-0.18.2
Build log ( /private/var/folders/v8/mpmmts8946j10dzhv2gxvt1h0000gp/T/tmp.2WNbluE5/mafia/.cabal-sandbox/logs/semigroups-0.18.2.log ):
Configuring semigroups-0.18.2...
Building semigroups-0.18.2...
Preprocessing library semigroups-0.18.2...
<command line>: cannot satisfy -package-id hashable-1.2.3.3-0878f5277d2f75c9c528bcea05099169
    (use -v for more information)
```

I'd look in the log file in the above message to see if there was any further clue as to why hashable failed.

**Comment by jacobstanley** [comment]
@newhoggy can you run `ghc-pkg list` and paste the output in here? cheers

**Comment by newhoggy** [comment]
This is what I have:

```
08:24 $ ghc-pkg list
WARNING: cache is out of date: /Library/Frameworks/GHC.framework/Versions/7.10.3-x86_64/usr/lib/ghc-7.10.3/package.conf.d/package.cache
ghc will see an old view of this package db. Use 'ghc-pkg recache' to fix.
/Library/Frameworks/GHC.framework/Versions/7.10.3-x86_64/usr/lib/ghc-7.10.3/package.conf.d
   Cabal-1.22.5.0
   GLURaw-1.5.0.2
   GLUT-2.7.0.3
   HTTP-4000.2.20
   HUnit-1.3.0.0
   ObjectName-1.1.0.0
   OpenGL-2.13.1.0
   OpenGLRaw-2.6.0.0
   QuickCheck-2.8.1
   StateVar-1.1.0.1
   array-0.5.1.0
   async-2.0.2
   attoparsec-0.13.0.1
   base-4.8.2.0
   bin-package-db-0.0.0.0
   binary-0.7.5.0
   bytestring-0.10.6.0
   case-insensitive-1.2.0.5
   cgi-3001.2.2.2
   containers-0.5.6.2
   deepseq-1.4.1.1
   directory-1.2.2.0
   exceptions-0.8.0.2
   fgl-5.5.2.3
   filepath-1.4.0.0
   ghc-7.10.3
   ghc-prim-0.4.0.0
   half-0.2.2.1
   hashable-1.2.3.3
   haskeline-0.7.2.1
   haskell-src-1.0.2.0
   hoopl-3.10.0.2
   hpc-0.6.0.2
   hscolour-1.23
   html-1.0.1.2
   integer-gmp-1.0.0.0
   mtl-2.2.1
   multipart-0.1.2
   network-2.6.2.1
   network-uri-2.6.0.3
   old-locale-1.0.0.7
   old-time-1.1.0.3
   parallel-3.2.0.6
   parsec-3.1.9
   pretty-1.1.2.0
   primitive-0.6.1.0
   process-1.2.3.0
   random-1.1
   regex-base-0.93.2
   regex-compat-0.95.1
   regex-posix-0.95.2
   rts-1.0
   scientific-0.3.3.8
   split-0.2.2
   stm-2.4.4
   syb-0.6
   template-haskell-2.10.0.0
   terminfo-0.4.0.1
   text-1.2.1.3
   tf-random-0.5
   time-1.5.0.1
   transformers-0.4.2.0
   transformers-compat-0.4.0.4
   unix-2.7.1.0
   unordered-containers-0.2.5.1
   vector-0.11.0.0
   xhtml-3000.2.1
   zlib-0.5.4.2
```

**Comment by jacobstanley** [comment]
Wow that looks really bad 😨 I wouldn't have expected so many packages installed globally, that will really mess things up.

For example, my `ghc-pkg list` for 7.10.2 looks like this:

```
/Users/jstanley/haskell/ghc-7.10.2/lib/ghc-7.10.2/package.conf.d
   Cabal-1.22.4.0
   array-0.5.1.0
   base-4.8.1.0
   bin-package-db-0.0.0.0
   binary-0.7.5.0
   bytestring-0.10.6.0
   containers-0.5.6.2
   deepseq-1.4.1.1
   directory-1.2.2.0
   filepath-1.4.0.0
   ghc-7.10.2
   ghc-prim-0.4.0.0
   haskeline-0.7.2.1
   hoopl-3.10.0.2
   hpc-0.6.0.2
   integer-gmp-1.0.0.0
   pretty-1.1.2.0
   process-1.2.3.0
   rts-1.0
   template-haskell-2.10.0.0
   terminfo-0.4.0.1
   time-1.5.0.1
   transformers-0.4.2.0
   unix-2.7.1.0
   xhtml-3000.2.1
/Users/jstanley/.ghc/x86_64-darwin-7.10.2/package.conf.d
   Cabal-1.23.0.0
   Cabal-1.23.1.0
   Cabal-1.24.0.0
```

How did you install ghc, is that haskell platform or something?

**Comment by newhoggy** [comment]
Yeah, Haskell Platform.  Should I uninstall everything and install the minimal version?

**Comment by jacobstanley** [comment]
Yeah that sounds good, we normally install ghc from the binaries available [here](https://www.haskell.org/ghc/download)

**Comment by jacobstanley** [comment]
These instructions are perhaps a little out of date, but this is how we install [ghc](https://gist.github.com/jystic/efded8238bc4c64affb7) and [cabal](https://gist.github.com/jystic/691a7b240345fc4c53ee)

You should be right using GHC 7.10.3 (or 8.0.1) and Cabal-1.24.0.0 though, even though the instructions mention earlier versions.

**Comment by newhoggy** [comment]
Just trying it now.  I'm finding that `Cabal-1.24.0.0` won't compile with `8.0.1`:

```
[ 1 of 25] Compiling Data.Time.Clock.CTimeval ( lib/Data/Time/Clock/CTimeval.hs, dist/build/Data/Time/Clock/CTimeval.o )

lib/Data/Time/Clock/CTimeval.hs:7:1: warning: [-Wdeprecations]
    Module ‘Foreign.Safe’ is deprecated:
      Safe is now the default, please use Foreign instead

lib/Data/Time/Clock/CTimeval.hs:13:1: warning: [-Wtabs]
    Tab character found here, and in 16 further locations.
    Please use spaces instead.
[ 2 of 25] Compiling Data.Time.Clock.Scale ( lib/Data/Time/Clock/Scale.hs, dist/build/Data/Time/Clock/Scale.o )

lib/Data/Time/Clock/Scale.hs:53:10: error:
    • No instance for (GHC.Generics.Generic DiffTime)
        arising from a use of ‘Control.DeepSeq.$dmrnf’
    • In the expression: Control.DeepSeq.$dmrnf
      In an equation for ‘rnf’: rnf = Control.DeepSeq.$dmrnf
      In the instance declaration for ‘NFData DiffTime’

Error during cabal-install bootstrap:
Building the time package failed.
```

So I'm going with `7.10.3` for installing Cabal.

**Comment by newhoggy** [comment]
I can confirm that `mafia` is working for me now.  Thanks so much for all your help!  👍
