### PR TITLE
Bump version bounds to give a build plan on GHC 8.4

### PR DESCRIPTION
**Pull request by tmcgilchrist**
Fixup the build failures from https://github.com/haskell-mafia/mafia/pull/220

cc @gwils

### CODE REVIEW

**Comment by gwils** [comment]
In travis, GHC 8.4 will be happier with cabal 2.2, but if it works anyway then there's probably no need to change it.

**Comment by tmcgilchrist** [comment]
Working on supporting Cabal 2.2 and above.

Were there any particular errors or problems you found with 2.0 and GHC 8.4?

**Comment by gwils** [comment]
Nope, but this fails for me locally on GHC 8.0.2

```
src/Mafia/Process.hs:199:5: error:
    Not in scope: data constructor ‘ProcessInternals.OpenExtHandle’
    Perhaps you meant one of these:
      ‘ProcessInternals.OpenHandle’ (imported from System.Process.Internals),
      ‘ProcessInternals.UseHandle’ (imported from System.Process.Internals),
      ‘ProcessInternals.ClosedHandle’ (imported from System.Process.Internals)
    Module ‘System.Process.Internals’ does not export ‘OpenExtHandle’.

src/Mafia/Process.hs:481:7: error:
    Not in scope: ‘Process.use_process_jobs’
    Module ‘System.Process’ does not export ‘use_process_jobs’.
```

**Comment by tmcgilchrist** [comment]
The lower bounds on `process` are wrong, both those things came in with [process 1.5](https://hackage.haskell.org/package/process-1.5.0.0)

**Review by erikd — APPROVED** [review]
LGTM!
